### ISSUE TITLE
Link under ReadMe is Not Valid

### ISSUE THREAD

**Issue by rawsGit** [polarityio/mandiant-threat-intelligence#12]
Under ReadME.md, in the About Mandiant Threat Intelligence section there is a bad link to www.FireEye.com/intel.
![image](https://github.com/polarityio/mandiant-threat-intelligence/assets/24832389/8acbac6d-822c-41d3-832b-9c83b1a07207)

 Bad in the sense that it lands in an Error 1016 page
![image](https://github.com/polarityio/mandiant-threat-intelligence/assets/24832389/05eda81f-adbe-44f1-b579-792a30d0eeb5)

Desired outcome: Replace current link with better link. 
Suggested Link:  https://www.mandiant.com/advantage/threat-intelligence

**Comment by sarus** [comment]
Thank you for the report.  The latest version of the integration has this resolved.
